### ISSUE TITLE
Crash with AutoHUD 1.20.1

### ISSUE THREAD

**Issue by Felisinnn** [RedLime/DetailArmorBar#48]
Removing exordium does not fix this either. 
### Crash log: 
Description: Unexpected error

java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.class_4587.method_22903(class_4587.java:527)
	at mod.crend.autohud.render.AutoHudRenderer.preInject(AutoHudRenderer.java:46)
	at com.redlimerl.detailab.render.ArmorBarRenderer.handler$zfl000$autohud$autoHud$preRender(ArmorBarRenderer.java:520)
	at com.redlimerl.detailab.render.ArmorBarRenderer.render(ArmorBarRenderer.java)
	at net.minecraft.class_329.handler$dig000$detailab$renderArmorOverlay(class_329.java:10875)
	at net.minecraft.class_329.method_1760(class_329.java:886)
	at net.minecraft.class_329.mixinextras$bridge$method_1760$231(class_329.java)
	at net.minecraft.class_329.wrapOperation$fac000$immediatelyfast$batching(class_329.java:2415)
	at net.minecraft.class_329.mixinextras$bridge$wrapOperation$fac000$immediatelyfast$batching$256(class_329.java)
	at net.minecraft.class_329.wrapOperation$eaf000$exordium$renderPlayerHealthWrapper(class_329.java:13452)
	at net.minecraft.class_329.method_1753(class_329.java:214)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.class_4587.method_22903(class_4587.java:527)
	at mod.crend.autohud.render.AutoHudRenderer.preInject(AutoHudRenderer.java:46)
	at com.redlimerl.detailab.render.ArmorBarRenderer.handler$zfl000$autohud$autoHud$preRender(ArmorBarRenderer.java:520)
	at com.redlimerl.detailab.render.ArmorBarRenderer.render(ArmorBarRenderer.java)
	at net.minecraft.class_329.handler$dig000$detailab$renderArmorOverlay(class_329.java:10875)
	at net.minecraft.class_329.method_1760(class_329.java:886)
	at net.minecraft.class_329.mixinextras$bridge$method_1760$231(class_329.java)
	at net.minecraft.class_329.wrapOperation$fac000$immediatelyfast$batching(class_329.java:2415)
	at net.minecraft.class_329.mixinextras$bridge$wrapOperation$fac000$immediatelyfast$batching$256(class_329.java)
	at net.minecraft.class_329.wrapOperation$eaf000$exordium$renderPlayerHealthWrapper(class_329.java:13452)
	at net.minecraft.class_329.method_1753(class_329.java:214)
Mixins in Stacktrace:
	net.minecraft.class_4587:
		me.jellysquid.mods.sodium.mixin.features.render.immediate.matrix_stack.MatrixStackMixin (sodium.mixins.json)
	com.redlimerl.detailab.render.ArmorBarRenderer:
		mod.crend.autohud.compat.mixin.detailab.ArmorBarRendererMixin (autohud.compat.mixins.json)
	net.minecraft.class_329:
		dev.tr7zw.exordium.mixin.GuiHotbarMixin (exordium.mixins.json)
		me.jellysquid.mods.sodium.mixin.features.options.overlays.InGameHudMixin (sodium.mixins.json)
		dev.tr7zw.exordium.mixin.CrosshairMixin (exordium.mixins.json)
		ca.jtai.tiefix.mixin.mc62997.InGameHudMixin (TieFix.mixins.json)
		com.tterrag.blur.mixin.MixinInGameHud (mixins.blur.json)
		dynamic_fps.impl.mixin.GuiMixin (dynamic_fps.mixins.json)
		dev.tr7zw.exordium.mixin.VignetteMixin (exordium.mixins.json)
		dev.yurisuika.raised.mixin.client.gui.hud.InGameHudMixin$Post (raised.mixins.json)
		com.teamderpy.shouldersurfing.mixins.MixinGui2 (shouldersurfing.mixins.json)
		com.yungnickyoung.minecraft.travelerstitles.mixin.RenderGuiTickMixinFabric (travelerstitles_fabric.mixins.json)
		com.teamderpy.shouldersurfing.mixins.MixinGui (shouldersurfing.mixins.json)
		ru.octol1ttle.damagevignette.mixin.GuiMixin (DamageVignette-common.mixins.json)
		com.jahirtrap.healthindicator.init.mixin.GuiMixin (healthindicatortxf.mixins.json)
		dev.tr7zw.exordium.mixin.GuiDebugOverlayMixin (exordium.mixins.json)
		dev.tr7zw.exordium.mixin.GuiHealthMixin (exordium.mixins.json)
		xaero.common.mixin.MixinInGameHud (xaerominimap.mixins.json)
		dev.isxander.debugify.client.mixins.basic.mc55347.GuiMixin (debugify.client.mixins.json)
		mod.crend.dynamiccrosshair.mixin.InGameHudMixin (dynamiccrosshair-common.mixins.json)
		com.noxcrew.noxesium.mixin.GuiMixin (noxesium.mixins.json)
		dev.isxander.debugify.client.mixins.basic.mc79545.GuiMixin (debugify.client.mixins.json)
		net.trueHorse.wildToolAccess.mixin.InGameHudMixin (wildtoolaccess.mixins.json)
		com.redlimerl.detailab.mixins.ArmorBarMixin (detailab.mixins.json)
		fi.dy.masa.malilib.mixin.MixinInGameHud (mixins.malilib.json)
		me.cominixo.betterf3.mixin.autof3.AutomaticDebugMixin (betterf3.mixins.json)
		dlovin.inventoryhud.mixin.MixinOverlay (inventoryhud.mixins.json)
		ca.jtai.tiefix.mixin.mc79545.InGameHudMixin (TieFix.mixins.json)
		squeek.appleskin.mixin.InGameHudMixin (appleskin.mixins.json)
		io.github.thecsdev.tcdcommons.client.mixin.events.MixinInGameHud (tcdcommons.client.mixin.events.json)
		fuzs.puzzleslib.mixin.client.GuiFabricMixin (puzzleslib.fabric.mixins.json)
		me.cominixo.betterf3.mixin.debugcrosshair.DebugCrosshairMixin (betterf3.mixins.json)
		fabric.net.raphimc.immediatelyfast.fabric.injection.mixins.hud_batching.MixinInGameHud (fabric-immediatelyfast-fabric.mixins.json)
		pepjebs.thirdpersonmaps.mixin.ThirdPersonMapsMixin (thirdpersonmaps.mixins.json)
		mod.crend.autohud.fabric.mixin.gui.InGameHudMixin (autohud-fabric.mixins.json)
		dev.yurisuika.raised.mixin.client.gui.hud.InGameHudMixin$Pre (raised.mixins.json)
		net.coderbot.iris.mixin.gui.MixinGui (mixins.iris.json)
		dev.tr7zw.exordium.mixin.GuiExperienceMixin (exordium.mixins.json)
		net.blay09.mods.balm.mixin.GuiMixin (balm.mixins.json)
		net.bettercombat.mixin.client.InGameHudInject (bettercombat.mixins.json)
		carpet.mixins.Gui_tablistMixin (carpet.mixins.json)
		dev.isxander.debugify.client.mixins.basic.mc215531.GuiMixin (debugify.client.mixins.json)
		net.fabricmc.fabric.mixin.client.rendering.InGameHudMixin (fabric-rendering-v1.mixins.json)
		xaero.map.mixin.MixinInGameHud (xaeroworldmap.mixins.json)
		dev.tr7zw.exordium.mixin.GuiMixin (exordium.mixins.json)
		dev.tr7zw.exordium.mixin.ScoreboardMixin (exordium.mixins.json)
		net.xolt.freecam.mixins.InGameHudMixin (freecam.mixins.json)
		interactic.mixin.InGameHudMixin (interactic.mixins.json)
		com.glue_gunner4.fastportals.mixin.InGameHudMixin (fast-portals.mixins.json)
		mod.crend.autohud.mixin.gui.StatusEffectTimerMixin (autohud-common.mixins.json)
		me.cominixo.betterf3.mixin.scoreboard.ScoreboardMixin (betterf3.mixins.json)

**Comment by Zorklis** [comment]
DetailArmorBar seriously needs to support AutoHud. Also crashed on 1.20.3/1.20.4 as of - [ DetailArmorBar-2.6.3+1.20.4-fabric ]

**Comment by Zorklis** [comment]
java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.class_4587.method_22903(class_4587.java:527)
	at mod.crend.autohud.render.AutoHudRenderer.preInject(AutoHudRenderer.java:47)
	at com.redlimerl.detailab.render.ArmorBarRenderer.handler$zbh000$autohud$autoHud$preRender(ArmorBarRenderer.java:520)
	at com.redlimerl.detailab.render.ArmorBarRenderer.render(ArmorBarRenderer.java)
	at net.minecraft.class_329.handler$zop000$detailab$renderArmorOverlay(class_329.java:4978)
	at net.minecraft.class_329.method_1760(class_329.java:925)
	at net.minecraft.class_329.mixinextras$bridge$method_1760$127(class_329.java)
	at net.minecraft.class_329.wrapOperation$bnl000$immediatelyfast$batching(class_329.java:2018)
	at net.minecraft.class_329.method_1753(class_329.java:245)
	at net.minecraft.class_757.method_3192(class_757.java:912)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Crendgrim** [comment]
I have released a new version of AutoHUD (6.3.1 for 1.20.1 ; 6.5.1 for 1.20.2-1.20.4) that fixes this.
